cols_to_drop = ['Population: Age <18 (Personssort column)','Population: Age 18+ (Personssort column)','Population: Age 25+ (Personssort column)','Population: Age 65+ (Personssort column)', 'Male Population Age 25+: Less Than High School Graduation (Personssort column)',
'Female Population Age 25+: Less Than High School Graduation (Personssort column)', 'Male Population Age 25+: Less than 9th Grade (Personssort column)',
'Male Population Age 25+: Some High School, No Diploma (Personssort column)',
'Male Population Age 25+: High School Graduate (Personssort column)',
'Male Population Age 25+: Some College, No Diploma (Personssort column)',
"Male Population Age 25+: Associate's Degree (Personssort column)",
"Male Population Age 25+: Bachelor's Degree (Personssort column)",
"Male Population Age 25+: Master's Degree (Personssort column)",
'Male Population Age 25+: Professional Degree (Personssort column)',
'Male Population Age 25+: Doctorate Degree (Personssort column)',
'Female Population Age 25+: Less than 9th Grade (Personssort column)',
'Female Population Age 25+: Some High School, No Diploma (Personssort column)',
'Female Population Age 25+: High School Graduate (Personssort column)',
'Female Population Age 25+: Some College, No Diploma (Personssort column)',
"Female Population Age 25+: Associate's Degree (Personssort column)",
"Female Population Age 25+: Bachelor's Degree (Personssort column)",
"Female Population Age 25+: Master's Degree (Personssort column)",
'Female Population Age 25+: Professional Degree (Personssort column)',
'Female Population Age 25+: Doctorate Degree (Personssort column)', 'Employed Civilian 16+ by Industry: Accommdtn/Food Svcs (Personssort column)',
'Employed Civilian 16+ by Industry: Admin/Spprt/Waste Mgmt (Personssort column)',
'Employed Civilian 16+ by Industry: Agriculture/Forest/Fish/Hunt (Personssort column)',
'Employed Civilian 16+ by Industry: Entertainment/Rec Svcs (Personssort column)',
'Employed Civilian 16+ by Industry: Construction (Personssort column)',
'Employed Civilian 16+ by Industry: Educational Svcs (Personssort column)',
'Employed Civilian 16+ by Industry: Fin/Insur/RE/Rent/Lse (Personssort column)',
'Employed Civilian 16+ by Industry: Health Care/Soc Asst (Personssort column)',
'Employed Civilian 16+ by Industry: Information (Personssort column)',
'Employed Civilian 16+ by Industry: Mgmt of Companies (Personssort column)',
'Employed Civilian 16+ by Industry: Total Manufacturing (Personssort column)',
'Employed Civilian 16+ by Industry: Oth Svcs, Not Pub Admin (Personssort column)',
'Employed Civilian 16+ by Industry: Prof/Sci/Tech/Admin (Personssort column)',
'Employed Civilian 16+ by Industry: Public Administration (Personssort column)',
'Employed Civilian 16+ by Industry: Retail Trade (Personssort column)',
'Employed Civilian 16+ by Industry: Transport/Warehse/Utils (Personssort column)',
'Employed Civilian 16+ by Industry: Wholesale Trade (Personssort column)', 'American Indian/Alaskan Native Population: Female (Personssort column)',
 'American Indian/Alaskan Native Population: Male (Personssort column)', 'Asian Population: Female (Personssort column)',
 'Asian Population: Male (Personssort column)', 'Black/African American Population: Female (Personssort column)',
 'Black/African American Population: Male (Personssort column)', 'Population: Age 0-4 (Personssort column)',
 'Population: Age 10-14 (Personssort column)',
 'Population: Age 15-17 (Personssort column)',
 'Population: Age 18-20 (Personssort column)',
 'Population: Age 21-24 (Personssort column)',
 'Population: Age 25-34 (Personssort column)',
 'Population: Age 35-44 (Personssort column)',
 'Population: Age 45-54 (Personssort column)',
 'Population: Age 5-9 (Personssort column)',
 'Population: Age 55-64 (Personssort column)',
 'Population: Age 65-74 (Personssort column)',
 'Population: Age 75-84 (Personssort column)',
 'Population: Age 85+ (Personssort column)', 'Population Age 5+ (Personssort column)', 'Native Hawaiian/Pacific Islander Population: Female (Personssort column)',
 'Native Hawaiian/Pacific Islander Population: Male (Personssort column)',
 'Non-Hispanic/Latino Population (Personssort column)',
 'Non-Hispanic/Latino: 2+ Races (Personssort column)',
 'Non-Hispanic/Latino: American Indian/Alaska Native (Personssort column)',
 'Non-Hispanic/Latino: Asian (Personssort column)',
 'Non-Hispanic/Latino: Black/African American (Personssort column)',
 'Non-Hispanic/Latino: Native Hawaiian/Pacific Islander (Personssort column)',
 'Non-Hispanic/Latino: Some Other Race (Personssort column)',
 'Non-Hispanic/Latino: White (Personssort column)', 'Male Population: Age 0 - 4 (Personssort column)',
 'Male Population: Age 10 - 14 (Personssort column)',
 'Male Population: Age 15 - 17 (Personssort column)',
 'Male Population: Age 18 - 20 (Personssort column)',
 'Male Population: Age 18+ (Personssort column)',
 'Male Population: Age 21 - 24 (Personssort column)',
 'Male Population: Age 25 - 34 (Personssort column)',
 'Male Population: Age 35 - 44 (Personssort column)',
 'Male Population: Age 45 - 54 (Personssort column)',
 'Male Population: Age 5 - 9 (Personssort column)',
 'Male Population: Age 55 - 64 (Personssort column)',
 'Male Population: Age 65 - 74 (Personssort column)',
 'Male Population: Age 65+ (Personssort column)',
 'Male Population: Age 75 - 84 (Personssort column)',
 'Male Population: Age 85+ (Personssort column)',
 'Male Population: Under 18 (Personssort column)', 'Hispanic/Latino Population: 2+ Races (Personssort column)',
 'Hispanic/Latino Population: American Indian/Alaska Native (Personssort column)',
 'Hispanic/Latino Population: Asian (Personssort column)',
 'Hispanic/Latino Population: Black/African American (Personssort column)',
 'Hispanic/Latino Population: Female (Personssort column)',
 'Hispanic/Latino Population: Male (Personssort column)',
 'Hispanic/Latino Population: Native Hawaiian/Pacific Islander (Personssort column)',
 'Hispanic/Latino Population: Some Other Race (Personssort column)',
 'Hispanic/Latino Population: White (Personssort column)', 'Female Population: Age 0 - 4 (Personssort column)',
 'Female Population: Age 10 - 14 (Personssort column)',
 'Female Population: Age 15 - 17 (Personssort column)',
 'Female Population: Age 18 - 20 (Personssort column)',
 'Female Population: Age 18+ (Personssort column)',
 'Female Population: Age 21 - 24 (Personssort column)',
 'Female Population: Age 25 - 34 (Personssort column)',
 'Female Population: Age 35 - 44 (Personssort column)',
 'Female Population: Age 45 - 54 (Personssort column)',
 'Female Population: Age 5 - 9 (Personssort column)',
 'Female Population: Age 55 - 64 (Personssort column)',
 'Female Population: Age 65 - 74 (Personssort column)',
 'Female Population: Age 65+ (Personssort column)',
 'Female Population: Age 75 - 84 (Personssort column)',
 'Female Population: Age 85+ (Personssort column)',
 'Female Population: Under 18 (Personssort column)', '2+ Races Population (Personssort column)',
 '2+ Races Population: Female (Personssort column)',
 '2+ Races Population: Male (Personssort column)','Households with Children (Householdssort column)', 'Some Other Race Population (Personssort column)',
 'Some Other Race Population: Female (Personssort column)',
 'Some Other Race Population: Male (Personssort column)', 'White Population: Female (Personssort column)',
 'White Population: Male (Personssort column)','Population Age 25+: Some High School, No Diploma (Personssort column)','Population Age 25+: Less than 9th Grade (Personssort column)','Population Age 25+: High School Graduate (Personssort column)',
 'Population Age 25+ with Less Than High School Graduation (Personssort column)','Population Age 25+: Associate Degree (Personssort column)','Population Age 25+: Some College, No Degree (Personssort column)',
 'Population Age 25+: Professional Degree (Personssort column)',
 'Average Household Size (Personssort column)']

cols_papa = ["id",  'geopoint',
 'latitude zipcode',
 'longitude zipcode',
 'geopoint zipcode',
 'distance',
 'sourceURLs',
 'websites',
 'keys',
 'join_Average income',
 'join_Median income',
 'join_Number of household',
 'join_Population', "province", "country"]

cols_machine = ['Population (Personssort column)',
 'Households (Householdssort column)',
 'Housing Units (Housing unitssort column)',
 'Families (Familiessort column)',
 'Male Population (Personssort column)',
 'Female Population (Personssort column)',
 'Hispanic/Latino Population (Personssort column)',
 'White Population (Personssort column)',
 'Black/African American Population (Personssort column)',
 'American Indian/Alaskan Native Population (Personssort column)',
 'Asian Population (Personssort column)',
 'Native Hawaiian/Pacific Islander Population (Personssort column)',
 'Population Age 5+: Speak Only English at Home (Personssort column)',
 'Population Age 5+: Speak Spanish at Home (Personssort column)',
 'Population Age 5+: Speak Asian/Pacific Islander Language at Home (Personssort column)',
 'Population Age 5+: Speak Indo-European Language at Home (Personssort column)',
 'Population Age 5+: Speak Other Language at Home (Personssort column)',
 'Population Age 15+: Never Married (Personssort column)',
 'Population Age 15+: Married, Spouse Present (Personssort column)',
 'Population Age 15+: Married, Spouse Absent (Personssort column)',
 'Population Age 15+: Divorced (Personssort column)',
 'Population Age 15+: Widowed (Personssort column)',
 'Households: 1-Person Household (Householdssort column)',
 'Households: 2-Person Household (Householdssort column)',
 'Households: 3-Person Household (Householdssort column)',
 'Households: 4-Person Household (Householdssort column)',
 'Households: 5-Person Household (Householdssort column)',
 'Households: 6-Person Household (Householdssort column)',
 'Households: 7+ Person Household (Householdssort column)',
 'Household Income: < $15,000 (Householdssort column)',
 'Household Income: $15,000 - $24,999 (Householdssort column)',
 'Household Income: $25,000 - $34,999 (Householdssort column)',
 'Household Income: $35,000 - $49,999 (Householdssort column)',
 'Household Income: $50,000 - $74,999 (Householdssort column)',
 'Household Income: $75,000 - $99,999 (Householdssort column)',
 'Household Income: $100,000 - $124,999 (Householdssort column)',
 'Household Income: $125,000 - $149,999 (Householdssort column)',
 'Household Income: $150,000 - $199,999 (Householdssort column)',
 'Household Income: $200,000 - $249,999 (Householdssort column)',
 'Household Income: $250,000 - $499,999 (Householdssort column)',
 'Household Income: $500,000+ (Householdssort column)',
 "Population Age 25+: Bachelor's Degree (Personssort column)",
 "Population Age 25+: Master's Degree (Personssort column)",
 'Population Age 25+: Doctorate Degree (Personssort column)',
 'Employed Civilian 16+ by Occupation: Architect/Engineer (Personssort column)',
 'Employed Civilian 16+ by Occupation: Arts/Entertain/Sports (Personssort column)',
 'Employed Civilian 16+ by Occupation: Building Grounds Maint (Personssort column)',
 'Employed Civilian 16+ by Occupation: Business/Financial Ops (Personssort column)',
 'Employed Civilian 16+ by Occupation: Community/Soc Svcs (Personssort column)',
 'Employed Civilian 16+ by Occupation: Computer/Mathematical (Personssort column)',
 'Employed Civilian 16+ by Occupation: Construction/Extraction (Personssort column)',
 'Employed Civilian 16+ by Occupation: Edu/Training/Library (Personssort column)',
 'Employed Civilian 16+ by Occupation: Farm/Fish/Forestry (Personssort column)',
 'Employed Civilian 16+ by Occupation: Food Prep/Serving (Personssort column)',
 'Employed Civilian 16+ by Occupation: Health Practitioner/Tec (Personssort column)',
 'Employed Civilian 16+ by Occupation: Healthcare Support (Personssort column)',
 'Employed Civilian 16+ by Occupation: Maintenance Repair (Personssort column)',
 'Employed Civilian 16+ by Occupation: Legal (Personssort column)',
 'Employed Civilian 16+ by Occupation: Life/Phys/Soc Science (Personssort column)',
 'Employed Civilian 16+ by Occupation: Management (Personssort column)',
 'Employed Civilian 16+ by Occupation: Office/Admin Support (Personssort column)',
 'Employed Civilian 16+ by Occupation: Production (Personssort column)',
 'Employed Civilian 16+ by Occupation: Protective Svcs (Personssort column)',
 'Employed Civilian 16+ by Occupation: Sales/Related (Personssort column)',
 'Employed Civilian 16+ by Occupation: Personal Care/Svc (Personssort column)',
 'Employed Civilian 16+ by Occupation: Transportation/Moving (Personssort column)',
 'Employed Civilian 16+ by Occupation Group: White Collar (Personssort column)',
 'Employed Civilian 16+ by Occupation Group: Blue Collar (Personssort column)',
 'Employed Civilian 16+ by Occupation Group: Service and Farm (Personssort column)',
 'Population: Age 0-17 (Personssort column)',
 'Population: Age 18-24 (Personssort column)',
 'Population: Age 25-44 (Personssort column)',
 'Population: Age 45-64 (Personssort column)',
 'Population: Age 65 + (Personssort column)',
 'Male Population: Age 0-17 (Personssort column)',
 'Male Population: Age 18-24 (Personssort column)',
 'Male Population: Age 25-44 (Personssort column)',
 'Male Population: Age 45-64 (Personssort column)',
 'Male Population: Age 65 + (Personssort column)',
 'Female Population: Age 0-17 (Personssort column)',
 'Female Population: Age 18-24 (Personssort column)',
 'Female Population: Age 25-44 (Personssort column)',
 'Female Population: Age 45-64 (Personssort column)',
 'Female Population: Age 65 + (Personssort column)',
 'Population Age 25+: High School Graduate or less (Personssort column)',
 'Population Age 25+: Associate or less (Personssort column)',
 'review',
 'review_count']

rows_drop = ['9300 NW 77th Ave','13530 SW 152nd St','11500 SW 88th St','13810 SW 8th St','15770 SW 56th St.','8699 Sunset Dr','6702 Bird Rd #3','Concourse F 3rd Level','Nw 27th ave','SE 1st Ave']

def drop_columns(df, cols_to_drop):
    df = df.drop(cols_to_drop, axis=1)
    return df

def drop_columns_papa(df, cols_papa):
    df = df.drop(cols_papa, axis=1)
    return df

def drop_rows_papa(df, rows_drop):
    df = df.drop(df[df['address'] == rows_drop.index], inplace = True, axis= 1)
    return df

def select_col_machine(df, cols_machine):
    df = df[cols_machine]
    return df
